# Configuración para GitHub Pages
title: "RegistroDigital - Sistema de Registro Académico"
description: "Plataforma moderna para el registro y gestión de estudiantes y profesores"
baseurl: "/REGISTRODIGITAL.git.io" # para GitHub Pages
url: "https://francisco-campos-s.github.io" # tu URL de GitHub Pages

# Jekyll configuration
markdown: kramdown
highlighter: rouge
theme: minima

# Include/Exclude files
include:
  - css/
  - js/
  - php/
  - database/
  - README.md

exclude:
  - vendor
  - .bundle
  - .sass-cache
  - _sass
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Social media
github_username: Francisco-Campos-S

# SEO
lang: es
timezone: America/Mexico_City
